import '../models/tutor_model.dart';
import '../models/user_model.dart';

// ─────────────────────────────────────────────────────────────────────────────
// Unified user list.  Users who are also tutors have isTutor = true and
// tutor-specific fields populated.  Each entry includes mock email / password
// so the data store is ready for future authentication.
// ─────────────────────────────────────────────────────────────────────────────

/// The currently logged-in mock user (non-tutor student).
const AppUser kMockCurrentUser = AppUser(
  id: 'u1',
  name: 'Alex Chen',
  email: 'alex.chen@stanford.edu',
  password: 'password123',
  avatarUrl: 'https://i.pravatar.cc/300?img=52',
  university: 'Stanford University',
  major: 'Mechanical Engineering',
  phoneNumber: '+66890001111',
  isTutor: false,
);

/// 8 mock tutor-users (assignment requirement).
/// Every tutor is also a user — same database table in the future.
final List<AppUser> kMockUsers = [
  // ── Current logged-in user ──
  kMockCurrentUser,

  // ── Tutors ──
  const AppUser(
    id: '1',
    name: 'Sarah Jenkins',
    email: 'sarah.jenkins@chula.ac.th',
    password: 'tutor123',
    avatarUrl: 'assets/images/Sarah Jenkins.png',
    university: 'Chulalongkorn University',
    major: 'Mathematics',
    phoneNumber: '+66812345678',
    isTutor: true,
    profession: 'Mathematics Teaching Assistant',
    education: 'BSc Mathematics, Chulalongkorn University',
    bio:
        'Hi! I specialize in making complex math concepts simple and intuitive. '
        'With over 2 years of tutoring experience at the university level, '
        'I focus on building confidence alongside solving problems.',
    hourlyRate: 450,
    currency: 'THB',
    subjectTags: ['Calculus', 'Statistics', 'Linear Algebra'],
    averageRating: 4.9,
    totalReviews: 124,
    totalSessions: 312,
    yearLevel: '4th Year',
    lineId: 'sarahjenkins',
    instagramHandle: 'sarah.jenkins',
    verified: true,
  ),
  const AppUser(
    id: '2',
    name: 'David Chen',
    email: 'david.chen@tu.ac.th',
    password: 'tutor123',
    avatarUrl: 'assets/images/David Chen.png',
    university: 'Thammasat University',
    major: 'Computer Science',
    phoneNumber: '+66823456789',
    isTutor: true,
    profession: 'Junior Software Developer',
    education: 'BSc Computer Science, Thammasat University',
    bio:
        'I make programming and data structures easy to understand. '
        'Flexible schedule and patient teaching style.',
    hourlyRate: 400,
    currency: 'THB',
    subjectTags: ['Computer Science', 'Python', 'Data Structures'],
    averageRating: 4.7,
    totalReviews: 45,
    totalSessions: 128,
    yearLevel: '3rd Year',
    lineId: 'davidchen',
    instagramHandle: 'david.chen',
    verified: true,
  ),
  const AppUser(
    id: '3',
    name: 'Elena Rodriguez',
    email: 'elena.r@ku.ac.th',
    password: 'tutor123',
    avatarUrl: 'assets/images/Elena Rodriguez.png',
    university: 'Kasetsart University',
    major: 'Applied Mathematics',
    phoneNumber: '+66834567890',
    isTutor: true,
    profession: 'Certified Math Teacher',
    education: 'MSc Applied Mathematics, Kasetsart University',
    bio:
        'Certified math teacher with 5+ years experience. Patient and methodical '
        'approach with proven results for exam preparation.',
    hourlyRate: 550,
    currency: 'THB',
    subjectTags: ['Calculus', 'Physics', 'Chemistry'],
    averageRating: 5.0,
    totalReviews: 89,
    totalSessions: 420,
    yearLevel: 'Graduate',
    lineId: 'elenarodriguez',
    instagramHandle: 'elena.rodriguez',
    verified: true,
  ),
  const AppUser(
    id: '4',
    name: 'Somchai Patel',
    email: 'somchai.p@chula.ac.th',
    password: 'tutor123',
    avatarUrl: 'assets/images/Somchai Patel.png',
    university: 'Chulalongkorn University',
    major: 'Physics',
    phoneNumber: '+66845678901',
    isTutor: true,
    profession: 'Physics Lab Assistant',
    education: 'BSc Physics, Chulalongkorn University',
    bio:
        'Physics enthusiast who loves breaking down complex theories into '
        'real-world examples. Top of class 3 years running.',
    hourlyRate: 500,
    currency: 'THB',
    subjectTags: ['Physics', 'General Math', 'Calculus'],
    averageRating: 4.8,
    totalReviews: 76,
    totalSessions: 215,
    yearLevel: '4th Year',
    lineId: 'somchaip',
    instagramHandle: 'somchai.phys',
    verified: true,
  ),
  const AppUser(
    id: '5',
    name: 'Ploy Wongsakorn',
    email: 'ploy.w@mahidol.ac.th',
    password: 'tutor123',
    avatarUrl: 'assets/images/Ploy Wongsakorn.png',
    university: 'Mahidol University',
    major: 'Biology',
    phoneNumber: '+66856789012',
    isTutor: true,
    profession: 'Research Assistant – Genetics Lab',
    education: 'BSc Biology, Mahidol University',
    bio:
        'Biology major with a passion for genetics and molecular biology. '
        'I use diagrams and mnemonics to help you remember everything.',
    hourlyRate: 350,
    currency: 'THB',
    subjectTags: ['Biology', 'Chemistry', 'English'],
    averageRating: 4.6,
    totalReviews: 38,
    totalSessions: 95,
    yearLevel: '3rd Year',
    lineId: 'ployws',
    instagramHandle: 'ploy.bio',
    verified: false,
  ),
  const AppUser(
    id: '6',
    name: 'Natthapong Lee',
    email: 'natthapong.l@tu.ac.th',
    password: 'tutor123',
    avatarUrl: 'assets/images/Natthapong Lee.png',
    university: 'Thammasat University',
    major: 'History',
    phoneNumber: '+66867890123',
    isTutor: true,
    profession: 'Freelance Writer & Tutor',
    education: 'BA History, Thammasat University',
    bio:
        'History and English tutor who makes lessons come alive through '
        'storytelling. Great at essay structuring and critical analysis.',
    hourlyRate: 300,
    currency: 'THB',
    subjectTags: ['History', 'English'],
    averageRating: 4.5,
    totalReviews: 29,
    totalSessions: 67,
    yearLevel: '2nd Year',
    lineId: 'nattlee',
    instagramHandle: 'natthapong_learns',
    verified: true,
  ),
  const AppUser(
    id: '7',
    name: 'Ananya Sharma',
    email: 'ananya.s@mahidol.ac.th',
    password: 'tutor123',
    avatarUrl: 'assets/images/Ananya Sharma.png',
    university: 'Mahidol University',
    major: 'Chemistry',
    phoneNumber: '+66878901234',
    isTutor: true,
    profession: 'Organic Chemistry TA',
    education: 'BSc Chemistry, Mahidol University',
    bio:
        'Chemistry whiz who scored top marks in organic chem. '
        'Tutoring is my way of giving back — let me help you ace your exams!',
    hourlyRate: 420,
    currency: 'THB',
    subjectTags: ['Chemistry', 'Biology', 'General Math'],
    averageRating: 4.9,
    totalReviews: 62,
    totalSessions: 180,
    yearLevel: '4th Year',
    lineId: 'ananyachem',
    instagramHandle: 'ananya.chem',
    verified: true,
  ),
  const AppUser(
    id: '8',
    name: 'James Tanaka',
    email: 'james.t@kmutt.ac.th',
    password: 'tutor123',
    avatarUrl: 'assets/images/James Tanaka.png',
    university: 'KMUTT',
    major: 'Computer Engineering',
    phoneNumber: '+66889012345',
    isTutor: true,
    profession: 'Full-Stack Developer',
    education: 'MEng Computer Engineering, KMUTT',
    bio:
        'Full-stack developer turned CS tutor. I teach algorithms, web dev, '
        'and database design with hands-on coding exercises.',
    hourlyRate: 600,
    currency: 'THB',
    subjectTags: ['Computer Science', 'General Math', 'Physics'],
    averageRating: 4.8,
    totalReviews: 91,
    totalSessions: 275,
    yearLevel: 'Graduate',
    lineId: 'jamestanaka',
    instagramHandle: 'james.codes',
    verified: true,
  ),
];

/// Convenience: only tutor users (for home / search screens).
List<AppUser> get kMockTutorUsers =>
    kMockUsers.where((u) => u.isTutor).toList();

// ── Legacy Tutor list (keeps existing screens compiling while we migrate) ──
List<Tutor> get kMockTutors => kMockTutorUsers
    .map(
      (u) => Tutor(
        id: u.id,
        name: u.name,
        avatarUrl: u.avatarUrl,
        bio: u.bio ?? '',
        hourlyRate: u.hourlyRate ?? 0,
        currency: u.currency ?? 'THB',
        subjectTags: u.subjectTags,
        averageRating: u.averageRating,
        totalReviews: u.totalReviews,
        totalSessions: u.totalSessions,
        university: u.university,
        major: u.major,
        yearLevel: u.yearLevel ?? '',
        lineId: u.lineId,
        instagramHandle: u.instagramHandle,
        phoneNumber: u.phoneNumber,
        verified: u.verified,
      ),
    )
    .toList();

/// 15 mock reviews (assignment requirement).
final List<Review> kMockReviews = [
  Review(
    id: '1',
    tutorId: '1',
    studentName: 'Alex M.',
    studentAvatar: 'https://i.pravatar.cc/100?img=20',
    rating: 5,
    comment:
        'Sarah helped me ace my Calculus final. She explains concepts very '
        'clearly and uses great visual aids. Highly recommend!',
    likes: 12,
    createdAt: DateTime(2026, 2, 26),
  ),
  Review(
    id: '2',
    tutorId: '1',
    studentName: 'Jordan T.',
    studentAvatar: 'https://i.pravatar.cc/100?img=21',
    rating: 5,
    comment:
        'Excellent at statistics. Patient and well-prepared every session.',
    likes: 8,
    createdAt: DateTime(2026, 2, 21),
  ),
  Review(
    id: '3',
    tutorId: '1',
    studentName: 'Mina K.',
    studentAvatar: 'https://i.pravatar.cc/100?img=22',
    rating: 4,
    comment:
        'Good tutor overall. Sometimes goes a bit fast but always willing to repeat.',
    likes: 3,
    createdAt: DateTime(2026, 2, 15),
  ),
  Review(
    id: '4',
    tutorId: '2',
    studentName: 'Sam K.',
    studentAvatar: 'https://i.pravatar.cc/100?img=23',
    rating: 4,
    comment: 'Very helpful and patient with Python. Would book again!',
    likes: 5,
    createdAt: DateTime(2026, 2, 14),
  ),
  Review(
    id: '5',
    tutorId: '2',
    studentName: 'Nina P.',
    studentAvatar: 'https://i.pravatar.cc/100?img=24',
    rating: 5,
    comment:
        'David made data structures click for me. Great real-world examples.',
    likes: 9,
    createdAt: DateTime(2026, 2, 10),
  ),
  Review(
    id: '6',
    tutorId: '3',
    studentName: 'Tom R.',
    studentAvatar: 'https://i.pravatar.cc/100?img=25',
    rating: 5,
    comment: 'Elena is the best math tutor I have ever had. Period.',
    likes: 15,
    createdAt: DateTime(2026, 2, 8),
  ),
  Review(
    id: '7',
    tutorId: '3',
    studentName: 'Fern S.',
    studentAvatar: 'https://i.pravatar.cc/100?img=26',
    rating: 5,
    comment:
        'Helped me go from failing to getting an A in Physics. Incredible.',
    likes: 20,
    createdAt: DateTime(2026, 2, 5),
  ),
  Review(
    id: '8',
    tutorId: '4',
    studentName: 'Lee W.',
    studentAvatar: 'https://i.pravatar.cc/100?img=27',
    rating: 5,
    comment: 'Somchai explains physics with real-world demos. Super engaging.',
    likes: 7,
    createdAt: DateTime(2026, 2, 1),
  ),
  Review(
    id: '9',
    tutorId: '4',
    studentName: 'Pat C.',
    studentAvatar: 'https://i.pravatar.cc/100?img=28',
    rating: 4,
    comment: 'Solid tutor for Calculus. Always on time and prepared.',
    likes: 4,
    createdAt: DateTime(2026, 1, 28),
  ),
  Review(
    id: '10',
    tutorId: '5',
    studentName: 'Grace L.',
    studentAvatar: 'https://i.pravatar.cc/100?img=29',
    rating: 5,
    comment: "Ploy's mnemonics for Biology are a lifesaver during exams.",
    likes: 11,
    createdAt: DateTime(2026, 1, 25),
  ),
  Review(
    id: '11',
    tutorId: '6',
    studentName: 'Beam N.',
    studentAvatar: 'https://i.pravatar.cc/100?img=30',
    rating: 4,
    comment: 'Natthapong makes history interesting. Good essay feedback too.',
    likes: 6,
    createdAt: DateTime(2026, 1, 20),
  ),
  Review(
    id: '12',
    tutorId: '7',
    studentName: 'Ying R.',
    studentAvatar: 'https://i.pravatar.cc/100?img=31',
    rating: 5,
    comment:
        'Ananya is amazing at organic chemistry. Clear diagrams every time.',
    likes: 14,
    createdAt: DateTime(2026, 1, 15),
  ),
  Review(
    id: '13',
    tutorId: '7',
    studentName: 'Pete S.',
    studentAvatar: 'https://i.pravatar.cc/100?img=32',
    rating: 5,
    comment: 'Best chem tutor on the platform. Worth every baht.',
    likes: 10,
    createdAt: DateTime(2026, 1, 12),
  ),
  Review(
    id: '14',
    tutorId: '8',
    studentName: 'Oak D.',
    studentAvatar: 'https://i.pravatar.cc/100?img=33',
    rating: 5,
    comment:
        'James teaches algorithms like a pro. Hands-on coding in every session.',
    likes: 18,
    createdAt: DateTime(2026, 1, 8),
  ),
  Review(
    id: '15',
    tutorId: '8',
    studentName: 'Mint A.',
    studentAvatar: 'https://i.pravatar.cc/100?img=34',
    rating: 4,
    comment:
        'Very knowledgeable. Sometimes a bit advanced, but always clarifies when asked.',
    likes: 5,
    createdAt: DateTime(2026, 1, 3),
  ),
];
