// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOUi5_wFSv_xqfgFsa9P9N0_wPt2oDz2M',
    appId: '1:1061613682883:web:5ecd1a307307c37dd66276',
    messagingSenderId: '1061613682883',
    projectId: 'studier-78f4d',
    authDomain: 'studier-78f4d.firebaseapp.com',
    databaseURL: 'https://studier-78f4d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'studier-78f4d.firebasestorage.app',
    measurementId: 'G-WMFT7HHHYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKviNIMK391l55pQ_qmFnRD6jXk-d9M9A',
    appId: '1:1061613682883:android:3c970728005c98f7d66276',
    messagingSenderId: '1061613682883',
    projectId: 'studier-78f4d',
    databaseURL: 'https://studier-78f4d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'studier-78f4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSw_wX_mjZympiJ_OpcPNGzwv_BCsON1c',
    appId: '1:1061613682883:ios:22872a89e1805eced66276',
    messagingSenderId: '1061613682883',
    projectId: 'studier-78f4d',
    databaseURL: 'https://studier-78f4d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'studier-78f4d.firebasestorage.app',
    iosBundleId: 'com.studier.studierFlutter',
  );
}
