// App Constants
export const COLORS = {
  primary: '#13ec5b',
  primaryDark: '#0fae43',
  backgroundLight: '#f6f8f6',
  backgroundDark: '#102216',
  surfaceDark: '#183221',
  cardDark: '#1A2E22',
  white: '#FFFFFF',
  black: '#000000',
  gray: {
    50: '#f9fafb',
    100: '#f3f4f6',
    200: '#e5e7eb',
    300: '#d1d5db',
    400: '#9ca3af',
    500: '#6b7280',
    600: '#4b5563',
    700: '#374151',
    800: '#1f2937',
    900: '#111827',
  },
};

export const SUBJECTS = [
  'Calculus',
  'Physics',
  'General Math',
  'Chemistry',
  'Biology',
  'Computer Science',
  'English',
  'History',
];

export const SOCIAL_PLATFORMS = {
  LINE: 'line',
  INSTAGRAM: 'instagram',
};

// Mock tutor data
export const MOCK_TUTORS = [
  {
    id: '1',
    name: 'Sarah Jenkins',
    university: 'PhD Candidate, MIT',
    year: 'Class of 2026',
    major: 'Mathematics',
    bio: 'Hi! I specialize in making complex math concepts simple and intuitive. With over 2 years of tutoring experience at the university level, I focus on building confidence alongside solving problems.',
    rating: 4.9,
    reviews: 124,
    sessions: 12,
    hourlyRate: 40,
    subjects: ['Calculus 1', 'Statistics', 'Linear Algebra'],
    image: 'https://i.pravatar.cc/300?img=1',
    verified: true,
    totalStudents: 500,
    successRate: 98,
    yearsExperience: 2,
    about: 'Hi! I specialize in making complex math concepts simple and intuitive. With over 2 years of tutoring experience at the university level, I focus on building confidence alongside solving problems.',
    availableDays: ['Mon', 'Wed', 'Fri'],
    tags: ['Statistics', 'Limits', 'Stats'],
    lineId: 'sarahjenkins',
    instagramHandle: 'sarah.jenkins',
  },
  {
    id: '2',
    name: 'David Chen',
    university: 'NYU',
    year: 'Class of 2025',
    major: 'Python, Data Structures',
    bio: 'I make things and confidently easy to understand. Flexible schedule...',
    rating: 4.7,
    reviews: 45,
    sessions: 8,
    hourlyRate: 35,
    subjects: ['Python', 'Algebra'],
    image: 'https://i.pravatar.cc/300?img=12',
    verified: true,
    totalStudents: 300,
    successRate: 96,
    yearsExperience: 1.5,
    about: 'I make things and confidently easy to understand. Flexible schedule...',
    availableDays: ['Tue', 'Thu'],
    lineId: 'davidchen',
    instagramHandle: 'david.chen',
  },
  {
    id: '3',
    name: 'Elena Rodriguez',
    university: 'Professor, NYU',
    year: 'Class of 2024',
    major: 'Creative Writing',
    bio: 'Certified Math teacher with 5+ years experience. Patient and...',
    rating: 5.0,
    reviews: 89,
    sessions: 19,
    hourlyRate: 55,
    subjects: ['Calc III', 'Series'],
    image: 'https://i.pravatar.cc/300?img=5',
    verified: true,
    totalStudents: 400,
    successRate: 99,
    yearsExperience: 5,
    about: 'Certified Math teacher with 5+ years experience. Patient and...',
    availableDays: ['Mon', 'Tue', 'Thu', 'Fri'],
    lineId: 'elenarodriguez',
    instagramHandle: 'elena.rodriguez',
  },
];

export const MOCK_REVIEWS = [
  {
    id: '1',
    tutorId: '1',
    userName: 'Alex M.',
    userId: 'user1',
    rating: 5,
    date: '2 days ago',
    comment: 'Sarah helped me ace my Calculus final. She explains concepts very clearly and uses great visual aids. Highly recommend if you\'re struggling with integrals!',
    courseContext: 'Calculus II',
  },
  {
    id: '2',
    tutorId: '1',
    userName: 'Jordan T.',
    userId: 'user2',
    rating: 5,
    date: '1 week ago',
    comment: 'Great tutor, but sometimes uses a few unclear...',
    courseContext: 'Statistics 101',
  },
  {
    id: '3',
    tutorId: '2',
    userName: 'Sam K.',
    userId: 'user3',
    rating: 4,
    date: '2 weeks ago',
    comment: 'Very helpful and patient. Would book again!',
    courseContext: 'Linear Algebra',
  },
];

